import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import Slidebar from "@/components/Slidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Landson Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=" flex  ">
        <div className=" w-64   bg-green-300 ">
         
        </div>
        <div className=" w-full">
          <div className="   w-full z-50 ">
          <Navbar/>
          </div>

          <main className="  px-1 h-screen -z-50 w-full mt-14   ">{children}</main>
        </div>
        </div>
        </body>
    </html>
  );
}
